// PROJECT DATA (same skeleton data, can be shared or imported)
const PROJECTS = {
  studybuddy: {
    title: "StudyBuddy",
    tagline: "A peer to peer student collaboration platform.",
    role: "Solo Designer / Developer",
    duration: "Dec 2024 - Present",
    tools: ["Figma", "React", "Supabase", "Tailwind CSS"],
    status: "40% Complete til MVP",
    hero: "assets/Studybuddy-1.png",
    overview: "StudyBuddy is a collaborative learning platform designed to help students find reliable, cost-effective peer tutors and connect based on shared courses and skill exchange. The project aims to enhance the quality of tutoring by pairing students with tutors who are best suited to their individual academic needs. In addition, StudyBuddy centralizes study resources to reduce the barriers students often face when searching for support materials, making academic help more accessible and equitable.",
    process: ["Identify student pain points around studying",
              "Researching existing study tools and workflows",
              "Sketching user flows and wireframes",
              "Designing UI and interaction patterns",
              "Developing core features",
              "Testing usability and refining the experience"],
    gallery: ["assets/dashboard.png", "assets/find-tutors.png"],
    outcome: "This project focuses on establishing a strong foundation for a peer driven academic support platform. Early research highlights a demand for cost-effective tutoring and skill-based student matching. Next steps include launching the MVP, campus outreach, and exploring funding opportunities to grow StudyBuddy as a student-centered startup."
  },
  bioinformatics: {
    title: "Bioinformatics Research @ UW School of Environmental & Forest Sciences: Plant Microbiology",
    tagline: "Advancing Crop Health: Developing strain-specific primers (SSPs) for endophyte identification using PCR Methodologies.",
    role: "Undergrad Researcher",
    duration: "June 2023 - Sept 2024",
    tools: ["R", "Markdown", "Geneious Prime", "Unix & Bash Scripting"],
    status: "100% Complete",
    hero: "assets/second-presentation.png",
    pdf: "assets/Strain Specific Primers (SSPs) Protocol.pdf",
    overview: "This project focused on Endophytes, tiny organisms that live inside plants. We wanted to find a way to identify exactly which strain a specific endophyte belongs to. To do this, we used PCR (a methodology for magnifying DNA) and Strain Specific Primers (SSPs, which are an advanced technique used to identify special endophyte DNA sequences).",
    process: ["Download and organize raw genomic data",
              "Shred genomes into uniform segments",
              "Filter for unique sequences through local \"Blasting\"",
              "Verify uniqueness against global NCBI databases",
              "Design Strain-Specific Primers (SSPs)",
              "Map and validate primers on the original genome",
              "Build a searchable digital library",
              "Establish standardized design protocols"],
    gallery: ["assets/first-presentation.png", "assets/research-presentation.png", "assets/protocol.png"],
    outcome: "The project successfully delivered precise primers identifying specific endophytes through the development of Strain-Specific Primers (SSPs) for the DOE, Specialty Crops, and Synergy strains. By identifying them through global database filtering and genomic mapping, the research produced high fidelity primers that ensure exclusive detection via PCR without cross-reactivity. These tools are integrated into an interactive R Quarto searchable table, centralizing critical technical data like to streamline lab operations. Furthermore, the establishment of a formal Standard Operating Procedure (SOP) provides a reproducible framework for future research, transforming raw genomic data into a functional, organized, and reliable system for strain-level identification."
  },
  changeability: {//Important
    title: "Changeability",
    tagline: "Empowering Personal Sustainability: Scanning Waste and Tracking Footprints for a Greener Tomorrow.",
    role: "UX Designer & Researcher",
    duration: "2023",
    tools: ["Figma"],
    status: "Complete",
    hero: "assets/changeability.png",
    video: "assets/Changeability - SMACK(T).mp4", // Path to your .mp4
    pdf: "assets/Group Project SMACK (T) (1).pdf",
    overview: "Changeability is an all in one sustainability app designed to reduce individual waste and carbon emissions by transforming daily habits. Developed to address the confusion surrounding climate change contributors, the app provides users with tools to independently track their environmental impact. It bridges the gap between high-level climate data and personal action by offering a convenient way to manage waste, monitor dietary carbon footprints, and visualize overall sustainability improvements.",
    process: ["Problem Identification",
              "Feature Engineering",
              "Information Architecture Design",
              "Policy and Ethical Review",
              "Impact Analysis"],
    gallery: ["assets/changeability.png"],
    outcome: "The Changeability project created a user-friendly app designed to help people lower their environmental impact by changing their daily habits. A key feature is the waste scanner, which identifies items like plastic bottles and tells you exactly how to recycle or compost them to avoid mistakes. The app also tracks your carbon footprint by looking at what you eat, how you travel, and the utilities you use, showing your progress through simple monthly charts. To make learning fun, it includes educational cartoons and articles that explain sustainability for all ages. By showing people the real-world impact of their choices, the app helps them move toward a cleaner, more sustainable lifestyle."
  },
/*chique: {
    title: "Bioinformatics Research",
    tagline: "Skeleton tagline",
    role: "Designer",
    duration: "2024",
    tools: ["Figma"],
    status: "80% Complete",
    hero: "assets/images/bioinformatics/hero.png",
    overview: "Skeleton overview for Bioinformatics project.",
    process: ["Step 1", "Step 2", "Step 3"],
    gallery: ["assets/images/bioinformatics/1.png"],
    outcome: "Skeleton outcome for Bioinformatics."
  },*/
  eatTogether: { //Important
    title: "Eat Together",
    tagline: "Building Community Through Food: Leading the Design and Strategy for UW’s Social Dining App.",
    role: "Lead Designer & Researcher",
    duration: "2023",
    tools: ["Figma, Canva, ClickUp"],
    status: "In Progress",
    hero: "assets/eattogetherdesigns.png",
    liveSite: "https://www.eat-together.org/",
    pdf: "assets/Eat Together Poster (1).pdf",
    overview: "Eat Together is a mobile application developed at the University of Washington to tackle student isolation by connecting peers through shared meals. As the Lead Designer, I managed the design team and acted as the bridge between creative vision and technical execution. My role was to refine the app’s user experience to ensure intuitive social discovery and spearhead the marketing design strategy to drive campus-wide adoption.",
    process: ["Design Interviews & Surveys",
              "Cross-Functional Collaboration",
              "App Refinement",
              "Marketing & Outreach",
              "System Integration"],
    gallery: [],
    outcome: "The project resulted in a student-centered application that successfully launched at UW. Under my leadership, the design team delivered a streamlined user interface that made finding dining companions effortless. The marketing campaign, driven by my custom poster designs, successfully established Eat Together as a recognizable campus brand. Ultimately, the app evolved from a conceptual tool into a functional community-building platform, bridging the gap between digital interaction and real-world social connection."
  },/*
mlhHackathon: {
    title: "Bioinformatics Research",
    tagline: "Skeleton tagline",
    role: "Designer",
    duration: "2024",
    tools: ["Figma"],
    status: "80% Complete",
    hero: "assets/images/bioinformatics/hero.png",
    overview: "Skeleton overview for Bioinformatics project.",
    process: ["Step 1", "Step 2", "Step 3"],
    gallery: ["assets/images/bioinformatics/1.png"],
    outcome: "Skeleton outcome for Bioinformatics."
  },
  infoHackathon: { //Important
    title: "Changeability",
    tagline: "Skeleton tagline",
    role: "Designer",
    duration: "2023",
    tools: ["Figma"],
    status: "In Progress",
    hero: "assets/images/changeability/hero.png",
    overview: "Skeleton overview for Changeability project.",
    process: ["Step 1", "Step 2"],
    gallery: [],
    outcome: "Skeleton outcome for Changeability."
  },
  truckCalculator: {//Important
    title: "Bioinformatics Research",
    tagline: "Skeleton tagline",
    role: "Designer",
    duration: "2024",
    tools: ["Figma"],
    status: "80% Complete",
    hero: "assets/images/bioinformatics/hero.png",
    overview: "Skeleton overview for Bioinformatics project.",
    process: ["Step 1", "Step 2", "Step 3"],
    gallery: ["assets/images/bioinformatics/1.png"],
    outcome: "Skeleton outcome for Bioinformatics."
  },
  passwordGenerator: {
    title: "Changeability",
    tagline: "Skeleton tagline",
    role: "Designer",
    duration: "2023",
    tools: ["Figma"],
    status: "In Progress",
    hero: "assets/images/changeability/hero.png",
    overview: "Skeleton overview for Changeability project.",
    process: ["Step 1", "Step 2"],
    gallery: [],
    outcome: "Skeleton outcome for Changeability."
  },*/
};
